// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIndexGuard is an autogenerated mock type for the IndexGuard type
type MockIndexGuard struct {
	mock.Mock
}

type MockIndexGuard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexGuard) EXPECT() *MockIndexGuard_Expecter {
	return &MockIndexGuard_Expecter{mock: &_m.Mock}
}

// CheckMutationAllowed provides a mock function with no fields
func (_m *MockIndexGuard) CheckMutationAllowed() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckMutationAllowed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexGuard_CheckMutationAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMutationAllowed'
type MockIndexGuard_CheckMutationAllowed_Call struct {
	*mock.Call
}

// CheckMutationAllowed is a helper method to define mock.On call
func (_e *MockIndexGuard_Expecter) CheckMutationAllowed() *MockIndexGuard_CheckMutationAllowed_Call {
	return &MockIndexGuard_CheckMutationAllowed_Call{Call: _e.mock.On("CheckMutationAllowed")}
}

func (_c *MockIndexGuard_CheckMutationAllowed_Call) Run(run func()) *MockIndexGuard_CheckMutationAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndexGuard_CheckMutationAllowed_Call) Return(_a0 error) *MockIndexGuard_CheckMutationAllowed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexGuard_CheckMutationAllowed_Call) RunAndReturn(run func() error) *MockIndexGuard_CheckMutationAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexGuard creates a new instance of MockIndexGuard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexGuard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexGuard {
	mock := &MockIndexGuard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
