// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockResetter is an autogenerated mock type for the Resetter type
type MockResetter struct {
	mock.Mock
}

type MockResetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResetter) EXPECT() *MockResetter_Expecter {
	return &MockResetter_Expecter{mock: &_m.Mock}
}

// Reset provides a mock function with given fields: ctx
func (_m *MockResetter) Reset(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResetter_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockResetter_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockResetter_Expecter) Reset(ctx interface{}) *MockResetter_Reset_Call {
	return &MockResetter_Reset_Call{Call: _e.mock.On("Reset", ctx)}
}

func (_c *MockResetter_Reset_Call) Run(run func(ctx context.Context)) *MockResetter_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockResetter_Reset_Call) Return(_a0 error) *MockResetter_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResetter_Reset_Call) RunAndReturn(run func(context.Context) error) *MockResetter_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResetter creates a new instance of MockResetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResetter {
	mock := &MockResetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
