// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAPIKeyUpdater is an autogenerated mock type for the APIKeyUpdater type
type MockAPIKeyUpdater struct {
	mock.Mock
}

type MockAPIKeyUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyUpdater) EXPECT() *MockAPIKeyUpdater_Expecter {
	return &MockAPIKeyUpdater_Expecter{mock: &_m.Mock}
}

// SetAPIKey provides a mock function with given fields: key
func (_m *MockAPIKeyUpdater) SetAPIKey(key string) {
	_m.Called(key)
}

// MockAPIKeyUpdater_SetAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAPIKey'
type MockAPIKeyUpdater_SetAPIKey_Call struct {
	*mock.Call
}

// SetAPIKey is a helper method to define mock.On call
//   - key string
func (_e *MockAPIKeyUpdater_Expecter) SetAPIKey(key interface{}) *MockAPIKeyUpdater_SetAPIKey_Call {
	return &MockAPIKeyUpdater_SetAPIKey_Call{Call: _e.mock.On("SetAPIKey", key)}
}

func (_c *MockAPIKeyUpdater_SetAPIKey_Call) Run(run func(key string)) *MockAPIKeyUpdater_SetAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAPIKeyUpdater_SetAPIKey_Call) Return() *MockAPIKeyUpdater_SetAPIKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPIKeyUpdater_SetAPIKey_Call) RunAndReturn(run func(string)) *MockAPIKeyUpdater_SetAPIKey_Call {
	_c.Run(run)
	return _c
}

// NewMockAPIKeyUpdater creates a new instance of MockAPIKeyUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyUpdater {
	mock := &MockAPIKeyUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
