// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	llm "github.com/santaniello/athena/internal/domain/llm"
	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function with given fields: ctx, req
func (_m *MockProvider) Chat(ctx context.Context, req llm.ChatRequest) (llm.ChatResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 llm.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.ChatRequest) (llm.ChatResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, llm.ChatRequest) llm.ChatResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(llm.ChatResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, llm.ChatRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockProvider_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - req llm.ChatRequest
func (_e *MockProvider_Expecter) Chat(ctx interface{}, req interface{}) *MockProvider_Chat_Call {
	return &MockProvider_Chat_Call{Call: _e.mock.On("Chat", ctx, req)}
}

func (_c *MockProvider_Chat_Call) Run(run func(ctx context.Context, req llm.ChatRequest)) *MockProvider_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.ChatRequest))
	})
	return _c
}

func (_c *MockProvider_Chat_Call) Return(_a0 llm.ChatResponse, _a1 error) *MockProvider_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_Chat_Call) RunAndReturn(run func(context.Context, llm.ChatRequest) (llm.ChatResponse, error)) *MockProvider_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// ChatStream provides a mock function with given fields: ctx, req, handler
func (_m *MockProvider) ChatStream(ctx context.Context, req llm.ChatRequest, handler func(string) error) error {
	ret := _m.Called(ctx, req, handler)

	if len(ret) == 0 {
		panic("no return value specified for ChatStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.ChatRequest, func(string) error) error); ok {
		r0 = rf(ctx, req, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvider_ChatStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatStream'
type MockProvider_ChatStream_Call struct {
	*mock.Call
}

// ChatStream is a helper method to define mock.On call
//   - ctx context.Context
//   - req llm.ChatRequest
//   - handler func(string) error
func (_e *MockProvider_Expecter) ChatStream(ctx interface{}, req interface{}, handler interface{}) *MockProvider_ChatStream_Call {
	return &MockProvider_ChatStream_Call{Call: _e.mock.On("ChatStream", ctx, req, handler)}
}

func (_c *MockProvider_ChatStream_Call) Run(run func(ctx context.Context, req llm.ChatRequest, handler func(string) error)) *MockProvider_ChatStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.ChatRequest), args[2].(func(string) error))
	})
	return _c
}

func (_c *MockProvider_ChatStream_Call) Return(_a0 error) *MockProvider_ChatStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_ChatStream_Call) RunAndReturn(run func(context.Context, llm.ChatRequest, func(string) error) error) *MockProvider_ChatStream_Call {
	_c.Call.Return(run)
	return _c
}

// Embeddings provides a mock function with given fields: ctx, req
func (_m *MockProvider) Embeddings(ctx context.Context, req llm.EmbeddingRequest) (llm.EmbeddingResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Embeddings")
	}

	var r0 llm.EmbeddingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.EmbeddingRequest) (llm.EmbeddingResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, llm.EmbeddingRequest) llm.EmbeddingResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(llm.EmbeddingResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, llm.EmbeddingRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_Embeddings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embeddings'
type MockProvider_Embeddings_Call struct {
	*mock.Call
}

// Embeddings is a helper method to define mock.On call
//   - ctx context.Context
//   - req llm.EmbeddingRequest
func (_e *MockProvider_Expecter) Embeddings(ctx interface{}, req interface{}) *MockProvider_Embeddings_Call {
	return &MockProvider_Embeddings_Call{Call: _e.mock.On("Embeddings", ctx, req)}
}

func (_c *MockProvider_Embeddings_Call) Run(run func(ctx context.Context, req llm.EmbeddingRequest)) *MockProvider_Embeddings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.EmbeddingRequest))
	})
	return _c
}

func (_c *MockProvider_Embeddings_Call) Return(_a0 llm.EmbeddingResponse, _a1 error) *MockProvider_Embeddings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_Embeddings_Call) RunAndReturn(run func(context.Context, llm.EmbeddingRequest) (llm.EmbeddingResponse, error)) *MockProvider_Embeddings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
