// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	llm "github.com/santaniello/athena/internal/domain/llm"
	mock "github.com/stretchr/testify/mock"
)

// MockUsageRecorder is an autogenerated mock type for the UsageRecorder type
type MockUsageRecorder struct {
	mock.Mock
}

type MockUsageRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsageRecorder) EXPECT() *MockUsageRecorder_Expecter {
	return &MockUsageRecorder_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, entry
func (_m *MockUsageRecorder) Record(ctx context.Context, entry llm.UsageEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.UsageEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsageRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockUsageRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - entry llm.UsageEntry
func (_e *MockUsageRecorder_Expecter) Record(ctx interface{}, entry interface{}) *MockUsageRecorder_Record_Call {
	return &MockUsageRecorder_Record_Call{Call: _e.mock.On("Record", ctx, entry)}
}

func (_c *MockUsageRecorder_Record_Call) Run(run func(ctx context.Context, entry llm.UsageEntry)) *MockUsageRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.UsageEntry))
	})
	return _c
}

func (_c *MockUsageRecorder_Record_Call) Return(_a0 error) *MockUsageRecorder_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsageRecorder_Record_Call) RunAndReturn(run func(context.Context, llm.UsageEntry) error) *MockUsageRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsageRecorder creates a new instance of MockUsageRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsageRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsageRecorder {
	mock := &MockUsageRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
