// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	llm "github.com/santaniello/athena/internal/domain/llm"
	mock "github.com/stretchr/testify/mock"
)

// MockModelCatalog is an autogenerated mock type for the ModelCatalog type
type MockModelCatalog struct {
	mock.Mock
}

type MockModelCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelCatalog) EXPECT() *MockModelCatalog_Expecter {
	return &MockModelCatalog_Expecter{mock: &_m.Mock}
}

// ListModels provides a mock function with given fields: ctx
func (_m *MockModelCatalog) ListModels(ctx context.Context) ([]llm.ModelInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListModels")
	}

	var r0 []llm.ModelInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]llm.ModelInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []llm.ModelInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]llm.ModelInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelCatalog_ListModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModels'
type MockModelCatalog_ListModels_Call struct {
	*mock.Call
}

// ListModels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModelCatalog_Expecter) ListModels(ctx interface{}) *MockModelCatalog_ListModels_Call {
	return &MockModelCatalog_ListModels_Call{Call: _e.mock.On("ListModels", ctx)}
}

func (_c *MockModelCatalog_ListModels_Call) Run(run func(ctx context.Context)) *MockModelCatalog_ListModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockModelCatalog_ListModels_Call) Return(_a0 []llm.ModelInfo, _a1 error) *MockModelCatalog_ListModels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelCatalog_ListModels_Call) RunAndReturn(run func(context.Context) ([]llm.ModelInfo, error)) *MockModelCatalog_ListModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelCatalog creates a new instance of MockModelCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelCatalog {
	mock := &MockModelCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
