// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockModelContextResolver is an autogenerated mock type for the ModelContextResolver type
type MockModelContextResolver struct {
	mock.Mock
}

type MockModelContextResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelContextResolver) EXPECT() *MockModelContextResolver_Expecter {
	return &MockModelContextResolver_Expecter{mock: &_m.Mock}
}

// CachedContextLength provides a mock function with given fields: modelID
func (_m *MockModelContextResolver) CachedContextLength(modelID string) (int, bool) {
	ret := _m.Called(modelID)

	if len(ret) == 0 {
		panic("no return value specified for CachedContextLength")
	}

	var r0 int
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (int, bool)); ok {
		return rf(modelID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(modelID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(modelID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockModelContextResolver_CachedContextLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CachedContextLength'
type MockModelContextResolver_CachedContextLength_Call struct {
	*mock.Call
}

// CachedContextLength is a helper method to define mock.On call
//   - modelID string
func (_e *MockModelContextResolver_Expecter) CachedContextLength(modelID interface{}) *MockModelContextResolver_CachedContextLength_Call {
	return &MockModelContextResolver_CachedContextLength_Call{Call: _e.mock.On("CachedContextLength", modelID)}
}

func (_c *MockModelContextResolver_CachedContextLength_Call) Run(run func(modelID string)) *MockModelContextResolver_CachedContextLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockModelContextResolver_CachedContextLength_Call) Return(_a0 int, _a1 bool) *MockModelContextResolver_CachedContextLength_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelContextResolver_CachedContextLength_Call) RunAndReturn(run func(string) (int, bool)) *MockModelContextResolver_CachedContextLength_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshContextLength provides a mock function with given fields: ctx, modelID
func (_m *MockModelContextResolver) RefreshContextLength(ctx context.Context, modelID string) (int, error) {
	ret := _m.Called(ctx, modelID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshContextLength")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, modelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, modelID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, modelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelContextResolver_RefreshContextLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshContextLength'
type MockModelContextResolver_RefreshContextLength_Call struct {
	*mock.Call
}

// RefreshContextLength is a helper method to define mock.On call
//   - ctx context.Context
//   - modelID string
func (_e *MockModelContextResolver_Expecter) RefreshContextLength(ctx interface{}, modelID interface{}) *MockModelContextResolver_RefreshContextLength_Call {
	return &MockModelContextResolver_RefreshContextLength_Call{Call: _e.mock.On("RefreshContextLength", ctx, modelID)}
}

func (_c *MockModelContextResolver_RefreshContextLength_Call) Run(run func(ctx context.Context, modelID string)) *MockModelContextResolver_RefreshContextLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockModelContextResolver_RefreshContextLength_Call) Return(_a0 int, _a1 error) *MockModelContextResolver_RefreshContextLength_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelContextResolver_RefreshContextLength_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockModelContextResolver_RefreshContextLength_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelContextResolver creates a new instance of MockModelContextResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelContextResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelContextResolver {
	mock := &MockModelContextResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
