// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgePendingReconciliationNoChange(arg1) {
  return window['go']['desktop']['App']['AcknowledgePendingReconciliationNoChange'](arg1);
}

export function AcknowledgeReconciliationNoChange(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['AcknowledgeReconciliationNoChange'](arg1, arg2, arg3);
}

export function ApplyPendingReconciliationCreate(arg1, arg2) {
  return window['go']['desktop']['App']['ApplyPendingReconciliationCreate'](arg1, arg2);
}

export function ApplyPendingReconciliationRelate(arg1) {
  return window['go']['desktop']['App']['ApplyPendingReconciliationRelate'](arg1);
}

export function ApplyPendingReconciliationUpdate(arg1) {
  return window['go']['desktop']['App']['ApplyPendingReconciliationUpdate'](arg1);
}

export function ApplyReconciliationCreate(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['ApplyReconciliationCreate'](arg1, arg2, arg3, arg4);
}

export function ApplyReconciliationRelate(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ApplyReconciliationRelate'](arg1, arg2, arg3);
}

export function ApplyReconciliationUpdate(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ApplyReconciliationUpdate'](arg1, arg2, arg3);
}

export function ApproveKnowledgeItem(arg1) {
  return window['go']['desktop']['App']['ApproveKnowledgeItem'](arg1);
}

export function CountDraftKnowledgeItems() {
  return window['go']['desktop']['App']['CountDraftKnowledgeItems']();
}

export function CountPendingReconciliations() {
  return window['go']['desktop']['App']['CountPendingReconciliations']();
}

export function CountUnindexedKnowledgeItems() {
  return window['go']['desktop']['App']['CountUnindexedKnowledgeItems']();
}

export function CreateFolder(arg1) {
  return window['go']['desktop']['App']['CreateFolder'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['desktop']['App']['DeleteFolder'](arg1);
}

export function DeleteKnowledgeItem(arg1) {
  return window['go']['desktop']['App']['DeleteKnowledgeItem'](arg1);
}

export function DeleteStudySession(arg1) {
  return window['go']['desktop']['App']['DeleteStudySession'](arg1);
}

export function DeprecateKnowledgeItem(arg1) {
  return window['go']['desktop']['App']['DeprecateKnowledgeItem'](arg1);
}

export function DiscardExtraction(arg1) {
  return window['go']['desktop']['App']['DiscardExtraction'](arg1);
}

export function ExtractKnowledge(arg1, arg2) {
  return window['go']['desktop']['App']['ExtractKnowledge'](arg1, arg2);
}

export function GetKnowledgeExtractionSettings() {
  return window['go']['desktop']['App']['GetKnowledgeExtractionSettings']();
}

export function GetKnowledgeIndexStatus() {
  return window['go']['desktop']['App']['GetKnowledgeIndexStatus']();
}

export function GetProfile() {
  return window['go']['desktop']['App']['GetProfile']();
}

export function HasLocalSession() {
  return window['go']['desktop']['App']['HasLocalSession']();
}

export function HasOpenRouterKey() {
  return window['go']['desktop']['App']['HasOpenRouterKey']();
}

export function HasUserProfile() {
  return window['go']['desktop']['App']['HasUserProfile']();
}

export function ImportFile(arg1) {
  return window['go']['desktop']['App']['ImportFile'](arg1);
}

export function ImportNotes(arg1) {
  return window['go']['desktop']['App']['ImportNotes'](arg1);
}

export function ListFolders() {
  return window['go']['desktop']['App']['ListFolders']();
}

export function ListKnowledgeItemEvidence(arg1) {
  return window['go']['desktop']['App']['ListKnowledgeItemEvidence'](arg1);
}

export function ListKnowledgeItems(arg1, arg2) {
  return window['go']['desktop']['App']['ListKnowledgeItems'](arg1, arg2);
}

export function ListKnowledgeTopics() {
  return window['go']['desktop']['App']['ListKnowledgeTopics']();
}

export function ListPendingReconciliations() {
  return window['go']['desktop']['App']['ListPendingReconciliations']();
}

export function ListStudySessionsByFolder(arg1) {
  return window['go']['desktop']['App']['ListStudySessionsByFolder'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['desktop']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['desktop']['App']['Logout']();
}

export function MoveStudySession(arg1, arg2) {
  return window['go']['desktop']['App']['MoveStudySession'](arg1, arg2);
}

export function PickNotesFile() {
  return window['go']['desktop']['App']['PickNotesFile']();
}

export function PickNotesFolder() {
  return window['go']['desktop']['App']['PickNotesFolder']();
}

export function Register(arg1, arg2) {
  return window['go']['desktop']['App']['Register'](arg1, arg2);
}

export function ReindexKnowledgeItems() {
  return window['go']['desktop']['App']['ReindexKnowledgeItems']();
}

export function RejectPendingReconciliationProposal(arg1) {
  return window['go']['desktop']['App']['RejectPendingReconciliationProposal'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['desktop']['App']['RenameFolder'](arg1, arg2);
}

export function RequestOpeningTurn(arg1, arg2) {
  return window['go']['desktop']['App']['RequestOpeningTurn'](arg1, arg2);
}

export function ResetLocalAccount(arg1) {
  return window['go']['desktop']['App']['ResetLocalAccount'](arg1);
}

export function ResolvePendingReconciliationConflict(arg1, arg2) {
  return window['go']['desktop']['App']['ResolvePendingReconciliationConflict'](arg1, arg2);
}

export function ResolveReconciliationConflict(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['ResolveReconciliationConflict'](arg1, arg2, arg3, arg4);
}

export function ResumeStudySession(arg1) {
  return window['go']['desktop']['App']['ResumeStudySession'](arg1);
}

export function RetryKnowledgeIndex() {
  return window['go']['desktop']['App']['RetryKnowledgeIndex']();
}

export function SaveAndApproveExtractedKnowledge(arg1, arg2) {
  return window['go']['desktop']['App']['SaveAndApproveExtractedKnowledge'](arg1, arg2);
}

export function SaveExtractedKnowledge(arg1, arg2) {
  return window['go']['desktop']['App']['SaveExtractedKnowledge'](arg1, arg2);
}

export function SaveOpenRouterKey(arg1) {
  return window['go']['desktop']['App']['SaveOpenRouterKey'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['desktop']['App']['SaveProfile'](arg1);
}

export function SaveReconciliationForReview(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SaveReconciliationForReview'](arg1, arg2, arg3);
}

export function SendStudyMessage(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SendStudyMessage'](arg1, arg2, arg3, arg4);
}

export function StartKnowledgeIndex(arg1) {
  return window['go']['desktop']['App']['StartKnowledgeIndex'](arg1);
}

export function StartStudySession(arg1, arg2) {
  return window['go']['desktop']['App']['StartStudySession'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}

export function UpdateKnowledgeExtractionSettings(arg1) {
  return window['go']['desktop']['App']['UpdateKnowledgeExtractionSettings'](arg1);
}

export function UpdateKnowledgeItem(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateKnowledgeItem'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['desktop']['App']['UpdateProfile'](arg1);
}
