// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveKnowledgeItem(arg1) {
  return window['go']['desktop']['App']['ApproveKnowledgeItem'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['desktop']['App']['CreateFolder'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['desktop']['App']['DeleteFolder'](arg1);
}

export function DeleteKnowledgeItem(arg1) {
  return window['go']['desktop']['App']['DeleteKnowledgeItem'](arg1);
}

export function DeleteStudySession(arg1) {
  return window['go']['desktop']['App']['DeleteStudySession'](arg1);
}

export function DeprecateKnowledgeItem(arg1) {
  return window['go']['desktop']['App']['DeprecateKnowledgeItem'](arg1);
}

export function ExtractKnowledge(arg1, arg2) {
  return window['go']['desktop']['App']['ExtractKnowledge'](arg1, arg2);
}

export function GetKnowledgeExtractionSettings() {
  return window['go']['desktop']['App']['GetKnowledgeExtractionSettings']();
}

export function GetKnowledgeIndexStatus() {
  return window['go']['desktop']['App']['GetKnowledgeIndexStatus']();
}

export function GetProfile() {
  return window['go']['desktop']['App']['GetProfile']();
}

export function HasLocalSession() {
  return window['go']['desktop']['App']['HasLocalSession']();
}

export function HasOpenRouterKey() {
  return window['go']['desktop']['App']['HasOpenRouterKey']();
}

export function HasUserProfile() {
  return window['go']['desktop']['App']['HasUserProfile']();
}

export function ImportFile(arg1) {
  return window['go']['desktop']['App']['ImportFile'](arg1);
}

export function ImportNotes(arg1) {
  return window['go']['desktop']['App']['ImportNotes'](arg1);
}

export function ListFolders() {
  return window['go']['desktop']['App']['ListFolders']();
}

export function ListKnowledgeItems(arg1, arg2) {
  return window['go']['desktop']['App']['ListKnowledgeItems'](arg1, arg2);
}

export function ListKnowledgeTopics() {
  return window['go']['desktop']['App']['ListKnowledgeTopics']();
}

export function ListStudySessionsByFolder(arg1) {
  return window['go']['desktop']['App']['ListStudySessionsByFolder'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['desktop']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['desktop']['App']['Logout']();
}

export function MoveStudySession(arg1, arg2) {
  return window['go']['desktop']['App']['MoveStudySession'](arg1, arg2);
}

export function PickNotesFile() {
  return window['go']['desktop']['App']['PickNotesFile']();
}

export function PickNotesFolder() {
  return window['go']['desktop']['App']['PickNotesFolder']();
}

export function Register(arg1, arg2) {
  return window['go']['desktop']['App']['Register'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['desktop']['App']['RenameFolder'](arg1, arg2);
}

export function RequestOpeningTurn(arg1, arg2) {
  return window['go']['desktop']['App']['RequestOpeningTurn'](arg1, arg2);
}

export function ResetLocalAccount(arg1) {
  return window['go']['desktop']['App']['ResetLocalAccount'](arg1);
}

export function ResumeStudySession(arg1) {
  return window['go']['desktop']['App']['ResumeStudySession'](arg1);
}

export function RetryKnowledgeIndex() {
  return window['go']['desktop']['App']['RetryKnowledgeIndex']();
}

export function SaveAndApproveExtractedKnowledge(arg1) {
  return window['go']['desktop']['App']['SaveAndApproveExtractedKnowledge'](arg1);
}

export function SaveExtractedKnowledge(arg1) {
  return window['go']['desktop']['App']['SaveExtractedKnowledge'](arg1);
}

export function SaveOpenRouterKey(arg1) {
  return window['go']['desktop']['App']['SaveOpenRouterKey'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['desktop']['App']['SaveProfile'](arg1);
}

export function SendStudyMessage(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SendStudyMessage'](arg1, arg2, arg3, arg4);
}

export function StartKnowledgeIndex(arg1) {
  return window['go']['desktop']['App']['StartKnowledgeIndex'](arg1);
}

export function StartStudySession(arg1, arg2) {
  return window['go']['desktop']['App']['StartStudySession'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}

export function UpdateKnowledgeExtractionSettings(arg1) {
  return window['go']['desktop']['App']['UpdateKnowledgeExtractionSettings'](arg1);
}

export function UpdateKnowledgeItem(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateKnowledgeItem'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['desktop']['App']['UpdateProfile'](arg1);
}
