// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndStudySession(arg1) {
  return window['go']['desktop']['App']['EndStudySession'](arg1);
}

export function GetProfile() {
  return window['go']['desktop']['App']['GetProfile']();
}

export function HasLocalSession() {
  return window['go']['desktop']['App']['HasLocalSession']();
}

export function HasOpenRouterKey() {
  return window['go']['desktop']['App']['HasOpenRouterKey']();
}

export function HasUserProfile() {
  return window['go']['desktop']['App']['HasUserProfile']();
}

export function Login(arg1, arg2) {
  return window['go']['desktop']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['desktop']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['desktop']['App']['Register'](arg1, arg2);
}

export function RequestOpeningTurn(arg1, arg2) {
  return window['go']['desktop']['App']['RequestOpeningTurn'](arg1, arg2);
}

export function ResetLocalAccount(arg1) {
  return window['go']['desktop']['App']['ResetLocalAccount'](arg1);
}

export function SaveOpenRouterKey(arg1) {
  return window['go']['desktop']['App']['SaveOpenRouterKey'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['desktop']['App']['SaveProfile'](arg1);
}

export function SendStudyMessage(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SendStudyMessage'](arg1, arg2, arg3);
}

export function StartStudySession(arg1) {
  return window['go']['desktop']['App']['StartStudySession'](arg1);
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}
