// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {context} from '../models';

export function ApproveKnowledgeItem(arg1:string):Promise<desktop.KnowledgeItemResult>;

export function CreateFolder(arg1:string):Promise<desktop.FolderResult>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteKnowledgeItem(arg1:string):Promise<void>;

export function DeleteStudySession(arg1:string):Promise<void>;

export function DeprecateKnowledgeItem(arg1:string):Promise<desktop.KnowledgeItemResult>;

export function ExtractKnowledge(arg1:string,arg2:boolean):Promise<desktop.ExtractionResult>;

export function GetKnowledgeExtractionSettings():Promise<desktop.KnowledgeExtractionSettings>;

export function GetKnowledgeIndexStatus():Promise<desktop.IndexStatusResult>;

export function GetProfile():Promise<desktop.UserProfileInput>;

export function HasLocalSession():Promise<boolean>;

export function HasOpenRouterKey():Promise<boolean>;

export function HasUserProfile():Promise<boolean>;

export function ImportNotes(arg1:string):Promise<void>;

export function ListFolders():Promise<Array<desktop.FolderResult>>;

export function ListKnowledgeItems(arg1:string,arg2:string):Promise<Array<desktop.KnowledgeItemResult>>;

export function ListKnowledgeTopics():Promise<Array<string>>;

export function ListStudySessionsByFolder(arg1:string):Promise<Array<desktop.StudySessionResult>>;

export function Login(arg1:string,arg2:string):Promise<desktop.LoginResult>;

export function Logout():Promise<void>;

export function MoveStudySession(arg1:string,arg2:string):Promise<void>;

export function PickNotesFolder():Promise<string>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RequestOpeningTurn(arg1:string,arg2:string):Promise<void>;

export function ResetLocalAccount(arg1:string):Promise<void>;

export function ResumeStudySession(arg1:string):Promise<desktop.StudySessionHistoryResult>;

export function RetryKnowledgeIndex():Promise<desktop.IndexStatusResult>;

export function SaveAndApproveExtractedKnowledge(arg1:Array<desktop.KnowledgeItemInput>):Promise<desktop.KnowledgeSaveResult>;

export function SaveExtractedKnowledge(arg1:Array<desktop.KnowledgeItemInput>):Promise<desktop.KnowledgeSaveResult>;

export function SaveOpenRouterKey(arg1:string):Promise<void>;

export function SaveProfile(arg1:desktop.UserProfileInput):Promise<void>;

export function SendStudyMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartKnowledgeIndex(arg1:context.Context):Promise<void>;

export function StartStudySession(arg1:string,arg2:string):Promise<desktop.StudySessionResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateKnowledgeExtractionSettings(arg1:number):Promise<void>;

export function UpdateKnowledgeItem(arg1:string,arg2:desktop.KnowledgeItemInput):Promise<desktop.KnowledgeItemResult>;

export function UpdateProfile(arg1:desktop.UserProfileInput):Promise<desktop.UserProfileInput>;
