// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockKnowledgeCascade is an autogenerated mock type for the KnowledgeCascade type
type MockKnowledgeCascade struct {
	mock.Mock
}

type MockKnowledgeCascade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKnowledgeCascade) EXPECT() *MockKnowledgeCascade_Expecter {
	return &MockKnowledgeCascade_Expecter{mock: &_m.Mock}
}

// DeleteSessionsWithKnowledge provides a mock function with given fields: ctx, sessionIDs, deleteSessions
func (_m *MockKnowledgeCascade) DeleteSessionsWithKnowledge(ctx context.Context, sessionIDs []string, deleteSessions func(context.Context) error) error {
	ret := _m.Called(ctx, sessionIDs, deleteSessions)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsWithKnowledge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, func(context.Context) error) error); ok {
		r0 = rf(ctx, sessionIDs, deleteSessions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsWithKnowledge'
type MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call struct {
	*mock.Call
}

// DeleteSessionsWithKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDs []string
//   - deleteSessions func(context.Context) error
func (_e *MockKnowledgeCascade_Expecter) DeleteSessionsWithKnowledge(ctx interface{}, sessionIDs interface{}, deleteSessions interface{}) *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call {
	return &MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call{Call: _e.mock.On("DeleteSessionsWithKnowledge", ctx, sessionIDs, deleteSessions)}
}

func (_c *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call) Run(run func(ctx context.Context, sessionIDs []string, deleteSessions func(context.Context) error)) *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call) Return(_a0 error) *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call) RunAndReturn(run func(context.Context, []string, func(context.Context) error) error) *MockKnowledgeCascade_DeleteSessionsWithKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKnowledgeCascade creates a new instance of MockKnowledgeCascade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKnowledgeCascade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKnowledgeCascade {
	mock := &MockKnowledgeCascade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
