// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockKeyValidator is an autogenerated mock type for the KeyValidator type
type MockKeyValidator struct {
	mock.Mock
}

type MockKeyValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyValidator) EXPECT() *MockKeyValidator_Expecter {
	return &MockKeyValidator_Expecter{mock: &_m.Mock}
}

// ValidateKey provides a mock function with given fields: ctx, key
func (_m *MockKeyValidator) ValidateKey(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ValidateKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyValidator_ValidateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateKey'
type MockKeyValidator_ValidateKey_Call struct {
	*mock.Call
}

// ValidateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockKeyValidator_Expecter) ValidateKey(ctx interface{}, key interface{}) *MockKeyValidator_ValidateKey_Call {
	return &MockKeyValidator_ValidateKey_Call{Call: _e.mock.On("ValidateKey", ctx, key)}
}

func (_c *MockKeyValidator_ValidateKey_Call) Run(run func(ctx context.Context, key string)) *MockKeyValidator_ValidateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockKeyValidator_ValidateKey_Call) Return(_a0 error) *MockKeyValidator_ValidateKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyValidator_ValidateKey_Call) RunAndReturn(run func(context.Context, string) error) *MockKeyValidator_ValidateKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyValidator creates a new instance of MockKeyValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyValidator {
	mock := &MockKeyValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
