// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	config "github.com/santaniello/athena/internal/domain/config"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockStore) Load() (config.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (config.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() config.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.Config)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockStore_Expecter) Load() *MockStore_Load_Call {
	return &MockStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockStore_Load_Call) Run(run func()) *MockStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Load_Call) Return(_a0 config.Config, _a1 error) *MockStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Load_Call) RunAndReturn(run func() (config.Config, error)) *MockStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: cfg
func (_m *MockStore) Save(cfg config.Config) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Config) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - cfg config.Config
func (_e *MockStore_Expecter) Save(cfg interface{}) *MockStore_Save_Call {
	return &MockStore_Save_Call{Call: _e.mock.On("Save", cfg)}
}

func (_c *MockStore_Save_Call) Run(run func(cfg config.Config)) *MockStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Config))
	})
	return _c
}

func (_c *MockStore_Save_Call) Return(_a0 error) *MockStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Save_Call) RunAndReturn(run func(config.Config) error) *MockStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
