// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	auth "github.com/santaniello/athena/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockSessionStore) Load() (auth.Session, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 auth.Session
	var r1 error
	if rf, ok := ret.Get(0).(func() (auth.Session, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() auth.Session); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(auth.Session)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSessionStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockSessionStore_Expecter) Load() *MockSessionStore_Load_Call {
	return &MockSessionStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockSessionStore_Load_Call) Run(run func()) *MockSessionStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionStore_Load_Call) Return(_a0 auth.Session, _a1 error) *MockSessionStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Load_Call) RunAndReturn(run func() (auth.Session, error)) *MockSessionStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: session
func (_m *MockSessionStore) Save(session auth.Session) error {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(auth.Session) error); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSessionStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - session auth.Session
func (_e *MockSessionStore_Expecter) Save(session interface{}) *MockSessionStore_Save_Call {
	return &MockSessionStore_Save_Call{Call: _e.mock.On("Save", session)}
}

func (_c *MockSessionStore_Save_Call) Run(run func(session auth.Session)) *MockSessionStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.Session))
	})
	return _c
}

func (_c *MockSessionStore_Save_Call) Return(_a0 error) *MockSessionStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Save_Call) RunAndReturn(run func(auth.Session) error) *MockSessionStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
