// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountByStatus provides a mock function with given fields: ctx, status
func (_m *MockRepository) CountByStatus(ctx context.Context, status string) (int, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *MockRepository_Expecter) CountByStatus(ctx interface{}, status interface{}) *MockRepository_CountByStatus_Call {
	return &MockRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, status)}
}

func (_c *MockRepository_CountByStatus_Call) Run(run func(ctx context.Context, status string)) *MockRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_CountByStatus_Call) Return(_a0 int, _a1 error) *MockRepository_CountByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountByStatus_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CountUnindexed provides a mock function with given fields: ctx, embeddingModel
func (_m *MockRepository) CountUnindexed(ctx context.Context, embeddingModel string) (int, error) {
	ret := _m.Called(ctx, embeddingModel)

	if len(ret) == 0 {
		panic("no return value specified for CountUnindexed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, embeddingModel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, embeddingModel)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, embeddingModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountUnindexed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnindexed'
type MockRepository_CountUnindexed_Call struct {
	*mock.Call
}

// CountUnindexed is a helper method to define mock.On call
//   - ctx context.Context
//   - embeddingModel string
func (_e *MockRepository_Expecter) CountUnindexed(ctx interface{}, embeddingModel interface{}) *MockRepository_CountUnindexed_Call {
	return &MockRepository_CountUnindexed_Call{Call: _e.mock.On("CountUnindexed", ctx, embeddingModel)}
}

func (_c *MockRepository_CountUnindexed_Call) Run(run func(ctx context.Context, embeddingModel string)) *MockRepository_CountUnindexed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_CountUnindexed_Call) Return(_a0 int, _a1 error) *MockRepository_CountUnindexed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountUnindexed_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRepository_CountUnindexed_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNormalizedConcept provides a mock function with given fields: ctx, topic, normalizedConcept
func (_m *MockRepository) FindByNormalizedConcept(ctx context.Context, topic string, normalizedConcept string) ([]knowledge.Item, error) {
	ret := _m.Called(ctx, topic, normalizedConcept)

	if len(ret) == 0 {
		panic("no return value specified for FindByNormalizedConcept")
	}

	var r0 []knowledge.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]knowledge.Item, error)); ok {
		return rf(ctx, topic, normalizedConcept)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []knowledge.Item); ok {
		r0 = rf(ctx, topic, normalizedConcept)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]knowledge.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, topic, normalizedConcept)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByNormalizedConcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNormalizedConcept'
type MockRepository_FindByNormalizedConcept_Call struct {
	*mock.Call
}

// FindByNormalizedConcept is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - normalizedConcept string
func (_e *MockRepository_Expecter) FindByNormalizedConcept(ctx interface{}, topic interface{}, normalizedConcept interface{}) *MockRepository_FindByNormalizedConcept_Call {
	return &MockRepository_FindByNormalizedConcept_Call{Call: _e.mock.On("FindByNormalizedConcept", ctx, topic, normalizedConcept)}
}

func (_c *MockRepository_FindByNormalizedConcept_Call) Run(run func(ctx context.Context, topic string, normalizedConcept string)) *MockRepository_FindByNormalizedConcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_FindByNormalizedConcept_Call) Return(_a0 []knowledge.Item, _a1 error) *MockRepository_FindByNormalizedConcept_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByNormalizedConcept_Call) RunAndReturn(run func(context.Context, string, string) ([]knowledge.Item, error)) *MockRepository_FindByNormalizedConcept_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTopic provides a mock function with given fields: ctx, topic
func (_m *MockRepository) FindByTopic(ctx context.Context, topic string) ([]knowledge.Item, error) {
	ret := _m.Called(ctx, topic)

	if len(ret) == 0 {
		panic("no return value specified for FindByTopic")
	}

	var r0 []knowledge.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]knowledge.Item, error)); ok {
		return rf(ctx, topic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []knowledge.Item); ok {
		r0 = rf(ctx, topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]knowledge.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTopic'
type MockRepository_FindByTopic_Call struct {
	*mock.Call
}

// FindByTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
func (_e *MockRepository_Expecter) FindByTopic(ctx interface{}, topic interface{}) *MockRepository_FindByTopic_Call {
	return &MockRepository_FindByTopic_Call{Call: _e.mock.On("FindByTopic", ctx, topic)}
}

func (_c *MockRepository_FindByTopic_Call) Run(run func(ctx context.Context, topic string)) *MockRepository_FindByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindByTopic_Call) Return(_a0 []knowledge.Item, _a1 error) *MockRepository_FindByTopic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByTopic_Call) RunAndReturn(run func(context.Context, string) ([]knowledge.Item, error)) *MockRepository_FindByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id string) (knowledge.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 knowledge.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (knowledge.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) knowledge.Item); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(knowledge.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 knowledge.Item, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (knowledge.Item, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRepository) List(ctx context.Context, filter knowledge.Filter) ([]knowledge.Item, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []knowledge.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Filter) ([]knowledge.Item, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Filter) []knowledge.Item); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]knowledge.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, knowledge.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter knowledge.Filter
func (_e *MockRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, filter knowledge.Filter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.Filter))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []knowledge.Item, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, knowledge.Filter) ([]knowledge.Item, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopics provides a mock function with given fields: ctx
func (_m *MockRepository) ListTopics(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTopics")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopics'
type MockRepository_ListTopics_Call struct {
	*mock.Call
}

// ListTopics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListTopics(ctx interface{}) *MockRepository_ListTopics_Call {
	return &MockRepository_ListTopics_Call{Call: _e.mock.On("ListTopics", ctx)}
}

func (_c *MockRepository_ListTopics_Call) Run(run func(ctx context.Context)) *MockRepository_ListTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListTopics_Call) Return(_a0 []string, _a1 error) *MockRepository_ListTopics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListTopics_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockRepository_ListTopics_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnindexed provides a mock function with given fields: ctx, embeddingModel
func (_m *MockRepository) ListUnindexed(ctx context.Context, embeddingModel string) ([]knowledge.Item, error) {
	ret := _m.Called(ctx, embeddingModel)

	if len(ret) == 0 {
		panic("no return value specified for ListUnindexed")
	}

	var r0 []knowledge.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]knowledge.Item, error)); ok {
		return rf(ctx, embeddingModel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []knowledge.Item); ok {
		r0 = rf(ctx, embeddingModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]knowledge.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, embeddingModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListUnindexed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnindexed'
type MockRepository_ListUnindexed_Call struct {
	*mock.Call
}

// ListUnindexed is a helper method to define mock.On call
//   - ctx context.Context
//   - embeddingModel string
func (_e *MockRepository_Expecter) ListUnindexed(ctx interface{}, embeddingModel interface{}) *MockRepository_ListUnindexed_Call {
	return &MockRepository_ListUnindexed_Call{Call: _e.mock.On("ListUnindexed", ctx, embeddingModel)}
}

func (_c *MockRepository_ListUnindexed_Call) Run(run func(ctx context.Context, embeddingModel string)) *MockRepository_ListUnindexed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_ListUnindexed_Call) Return(_a0 []knowledge.Item, _a1 error) *MockRepository_ListUnindexed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListUnindexed_Call) RunAndReturn(run func(context.Context, string) ([]knowledge.Item, error)) *MockRepository_ListUnindexed_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, item
func (_m *MockRepository) Save(ctx context.Context, item knowledge.Item) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Item) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - item knowledge.Item
func (_e *MockRepository_Expecter) Save(ctx interface{}, item interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, item)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, item knowledge.Item)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.Item))
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(_a0 error) *MockRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(context.Context, knowledge.Item) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, item
func (_m *MockRepository) Update(ctx context.Context, item knowledge.Item) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Item) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item knowledge.Item
func (_e *MockRepository_Expecter) Update(ctx interface{}, item interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, item knowledge.Item)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.Item))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, knowledge.Item) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
