// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockIngestedFileRepository is an autogenerated mock type for the IngestedFileRepository type
type MockIngestedFileRepository struct {
	mock.Mock
}

type MockIngestedFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestedFileRepository) EXPECT() *MockIngestedFileRepository_Expecter {
	return &MockIngestedFileRepository_Expecter{mock: &_m.Mock}
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockIngestedFileRepository) ListAll(ctx context.Context) (map[string]knowledge.IngestedFile, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 map[string]knowledge.IngestedFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]knowledge.IngestedFile, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]knowledge.IngestedFile); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]knowledge.IngestedFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIngestedFileRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockIngestedFileRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIngestedFileRepository_Expecter) ListAll(ctx interface{}) *MockIngestedFileRepository_ListAll_Call {
	return &MockIngestedFileRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockIngestedFileRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockIngestedFileRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIngestedFileRepository_ListAll_Call) Return(_a0 map[string]knowledge.IngestedFile, _a1 error) *MockIngestedFileRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIngestedFileRepository_ListAll_Call) RunAndReturn(run func(context.Context) (map[string]knowledge.IngestedFile, error)) *MockIngestedFileRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, file
func (_m *MockIngestedFileRepository) Upsert(ctx context.Context, file knowledge.IngestedFile) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.IngestedFile) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIngestedFileRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockIngestedFileRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - file knowledge.IngestedFile
func (_e *MockIngestedFileRepository_Expecter) Upsert(ctx interface{}, file interface{}) *MockIngestedFileRepository_Upsert_Call {
	return &MockIngestedFileRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, file)}
}

func (_c *MockIngestedFileRepository_Upsert_Call) Run(run func(ctx context.Context, file knowledge.IngestedFile)) *MockIngestedFileRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.IngestedFile))
	})
	return _c
}

func (_c *MockIngestedFileRepository_Upsert_Call) Return(_a0 error) *MockIngestedFileRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIngestedFileRepository_Upsert_Call) RunAndReturn(run func(context.Context, knowledge.IngestedFile) error) *MockIngestedFileRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngestedFileRepository creates a new instance of MockIngestedFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestedFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestedFileRepository {
	mock := &MockIngestedFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
