// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockRetriever is an autogenerated mock type for the Retriever type
type MockRetriever struct {
	mock.Mock
}

type MockRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetriever) EXPECT() *MockRetriever_Expecter {
	return &MockRetriever_Expecter{mock: &_m.Mock}
}

// Retrieve provides a mock function with given fields: ctx, sessionID, query
func (_m *MockRetriever) Retrieve(ctx context.Context, sessionID string, query string) (knowledge.RetrievalResult, error) {
	ret := _m.Called(ctx, sessionID, query)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 knowledge.RetrievalResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (knowledge.RetrievalResult, error)); ok {
		return rf(ctx, sessionID, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) knowledge.RetrievalResult); ok {
		r0 = rf(ctx, sessionID, query)
	} else {
		r0 = ret.Get(0).(knowledge.RetrievalResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionID, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRetriever_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockRetriever_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - query string
func (_e *MockRetriever_Expecter) Retrieve(ctx interface{}, sessionID interface{}, query interface{}) *MockRetriever_Retrieve_Call {
	return &MockRetriever_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, sessionID, query)}
}

func (_c *MockRetriever_Retrieve_Call) Run(run func(ctx context.Context, sessionID string, query string)) *MockRetriever_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRetriever_Retrieve_Call) Return(_a0 knowledge.RetrievalResult, _a1 error) *MockRetriever_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRetriever_Retrieve_Call) RunAndReturn(run func(context.Context, string, string) (knowledge.RetrievalResult, error)) *MockRetriever_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRetriever creates a new instance of MockRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetriever {
	mock := &MockRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
