// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockVectorStore is an autogenerated mock type for the VectorStore type
type MockVectorStore struct {
	mock.Mock
}

type MockVectorStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVectorStore) EXPECT() *MockVectorStore_Expecter {
	return &MockVectorStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, chunks
func (_m *MockVectorStore) Add(ctx context.Context, chunks []knowledge.Chunk) error {
	ret := _m.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []knowledge.Chunk) error); ok {
		r0 = rf(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVectorStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockVectorStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []knowledge.Chunk
func (_e *MockVectorStore_Expecter) Add(ctx interface{}, chunks interface{}) *MockVectorStore_Add_Call {
	return &MockVectorStore_Add_Call{Call: _e.mock.On("Add", ctx, chunks)}
}

func (_c *MockVectorStore_Add_Call) Run(run func(ctx context.Context, chunks []knowledge.Chunk)) *MockVectorStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]knowledge.Chunk))
	})
	return _c
}

func (_c *MockVectorStore_Add_Call) Return(_a0 error) *MockVectorStore_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVectorStore_Add_Call) RunAndReturn(run func(context.Context, []knowledge.Chunk) error) *MockVectorStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *MockVectorStore) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockVectorStore_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockVectorStore_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockVectorStore_Expecter) Len() *MockVectorStore_Len_Call {
	return &MockVectorStore_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockVectorStore_Len_Call) Run(run func()) *MockVectorStore_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVectorStore_Len_Call) Return(_a0 int) *MockVectorStore_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVectorStore_Len_Call) RunAndReturn(run func() int) *MockVectorStore_Len_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, ids
func (_m *MockVectorStore) Remove(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVectorStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockVectorStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockVectorStore_Expecter) Remove(ctx interface{}, ids interface{}) *MockVectorStore_Remove_Call {
	return &MockVectorStore_Remove_Call{Call: _e.mock.On("Remove", ctx, ids)}
}

func (_c *MockVectorStore_Remove_Call) Run(run func(ctx context.Context, ids []string)) *MockVectorStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockVectorStore_Remove_Call) Return(_a0 error) *MockVectorStore_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVectorStore_Remove_Call) RunAndReturn(run func(context.Context, []string) error) *MockVectorStore_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAll provides a mock function with given fields: ctx, chunks
func (_m *MockVectorStore) ReplaceAll(ctx context.Context, chunks []knowledge.Chunk) error {
	ret := _m.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []knowledge.Chunk) error); ok {
		r0 = rf(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVectorStore_ReplaceAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAll'
type MockVectorStore_ReplaceAll_Call struct {
	*mock.Call
}

// ReplaceAll is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []knowledge.Chunk
func (_e *MockVectorStore_Expecter) ReplaceAll(ctx interface{}, chunks interface{}) *MockVectorStore_ReplaceAll_Call {
	return &MockVectorStore_ReplaceAll_Call{Call: _e.mock.On("ReplaceAll", ctx, chunks)}
}

func (_c *MockVectorStore_ReplaceAll_Call) Run(run func(ctx context.Context, chunks []knowledge.Chunk)) *MockVectorStore_ReplaceAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]knowledge.Chunk))
	})
	return _c
}

func (_c *MockVectorStore_ReplaceAll_Call) Return(_a0 error) *MockVectorStore_ReplaceAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVectorStore_ReplaceAll_Call) RunAndReturn(run func(context.Context, []knowledge.Chunk) error) *MockVectorStore_ReplaceAll_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, topK, filters
func (_m *MockVectorStore) Search(ctx context.Context, query []float32, topK int, filters knowledge.SearchFilters) ([]knowledge.ScoredChunk, error) {
	ret := _m.Called(ctx, query, topK, filters)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []knowledge.ScoredChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []float32, int, knowledge.SearchFilters) ([]knowledge.ScoredChunk, error)); ok {
		return rf(ctx, query, topK, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []float32, int, knowledge.SearchFilters) []knowledge.ScoredChunk); ok {
		r0 = rf(ctx, query, topK, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]knowledge.ScoredChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []float32, int, knowledge.SearchFilters) error); ok {
		r1 = rf(ctx, query, topK, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVectorStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockVectorStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query []float32
//   - topK int
//   - filters knowledge.SearchFilters
func (_e *MockVectorStore_Expecter) Search(ctx interface{}, query interface{}, topK interface{}, filters interface{}) *MockVectorStore_Search_Call {
	return &MockVectorStore_Search_Call{Call: _e.mock.On("Search", ctx, query, topK, filters)}
}

func (_c *MockVectorStore_Search_Call) Run(run func(ctx context.Context, query []float32, topK int, filters knowledge.SearchFilters)) *MockVectorStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]float32), args[2].(int), args[3].(knowledge.SearchFilters))
	})
	return _c
}

func (_c *MockVectorStore_Search_Call) Return(_a0 []knowledge.ScoredChunk, _a1 error) *MockVectorStore_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVectorStore_Search_Call) RunAndReturn(run func(context.Context, []float32, int, knowledge.SearchFilters) ([]knowledge.ScoredChunk, error)) *MockVectorStore_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVectorStore creates a new instance of MockVectorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVectorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVectorStore {
	mock := &MockVectorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
