// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentRepository is an autogenerated mock type for the DocumentRepository type
type MockDocumentRepository struct {
	mock.Mock
}

type MockDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentRepository) EXPECT() *MockDocumentRepository_Expecter {
	return &MockDocumentRepository_Expecter{mock: &_m.Mock}
}

// DeleteByItemID provides a mock function with given fields: ctx, sessionID, itemID
func (_m *MockDocumentRepository) DeleteByItemID(ctx context.Context, sessionID string, itemID string) error {
	ret := _m.Called(ctx, sessionID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByItemID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_DeleteByItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByItemID'
type MockDocumentRepository_DeleteByItemID_Call struct {
	*mock.Call
}

// DeleteByItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - itemID string
func (_e *MockDocumentRepository_Expecter) DeleteByItemID(ctx interface{}, sessionID interface{}, itemID interface{}) *MockDocumentRepository_DeleteByItemID_Call {
	return &MockDocumentRepository_DeleteByItemID_Call{Call: _e.mock.On("DeleteByItemID", ctx, sessionID, itemID)}
}

func (_c *MockDocumentRepository_DeleteByItemID_Call) Run(run func(ctx context.Context, sessionID string, itemID string)) *MockDocumentRepository_DeleteByItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDocumentRepository_DeleteByItemID_Call) Return(_a0 error) *MockDocumentRepository_DeleteByItemID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_DeleteByItemID_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDocumentRepository_DeleteByItemID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, sessionID, itemID
func (_m *MockDocumentRepository) Get(ctx context.Context, sessionID string, itemID string) (string, error) {
	ret := _m.Called(ctx, sessionID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, sessionID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, sessionID, itemID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDocumentRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - itemID string
func (_e *MockDocumentRepository_Expecter) Get(ctx interface{}, sessionID interface{}, itemID interface{}) *MockDocumentRepository_Get_Call {
	return &MockDocumentRepository_Get_Call{Call: _e.mock.On("Get", ctx, sessionID, itemID)}
}

func (_c *MockDocumentRepository_Get_Call) Run(run func(ctx context.Context, sessionID string, itemID string)) *MockDocumentRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDocumentRepository_Get_Call) Return(_a0 string, _a1 error) *MockDocumentRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockDocumentRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, itemID, sessionID, content
func (_m *MockDocumentRepository) Save(ctx context.Context, itemID string, sessionID string, content string) error {
	ret := _m.Called(ctx, itemID, sessionID, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, itemID, sessionID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockDocumentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID string
//   - sessionID string
//   - content string
func (_e *MockDocumentRepository_Expecter) Save(ctx interface{}, itemID interface{}, sessionID interface{}, content interface{}) *MockDocumentRepository_Save_Call {
	return &MockDocumentRepository_Save_Call{Call: _e.mock.On("Save", ctx, itemID, sessionID, content)}
}

func (_c *MockDocumentRepository_Save_Call) Run(run func(ctx context.Context, itemID string, sessionID string, content string)) *MockDocumentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockDocumentRepository_Save_Call) Return(_a0 error) *MockDocumentRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_Save_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockDocumentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentRepository creates a new instance of MockDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepository {
	mock := &MockDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
