// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockReconciliationRepository is an autogenerated mock type for the ReconciliationRepository type
type MockReconciliationRepository struct {
	mock.Mock
}

type MockReconciliationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReconciliationRepository) EXPECT() *MockReconciliationRepository_Expecter {
	return &MockReconciliationRepository_Expecter{mock: &_m.Mock}
}

// LinkEvidence provides a mock function with given fields: ctx, proposalID, evidenceID
func (_m *MockReconciliationRepository) LinkEvidence(ctx context.Context, proposalID string, evidenceID string) error {
	ret := _m.Called(ctx, proposalID, evidenceID)

	if len(ret) == 0 {
		panic("no return value specified for LinkEvidence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, proposalID, evidenceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReconciliationRepository_LinkEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkEvidence'
type MockReconciliationRepository_LinkEvidence_Call struct {
	*mock.Call
}

// LinkEvidence is a helper method to define mock.On call
//   - ctx context.Context
//   - proposalID string
//   - evidenceID string
func (_e *MockReconciliationRepository_Expecter) LinkEvidence(ctx interface{}, proposalID interface{}, evidenceID interface{}) *MockReconciliationRepository_LinkEvidence_Call {
	return &MockReconciliationRepository_LinkEvidence_Call{Call: _e.mock.On("LinkEvidence", ctx, proposalID, evidenceID)}
}

func (_c *MockReconciliationRepository_LinkEvidence_Call) Run(run func(ctx context.Context, proposalID string, evidenceID string)) *MockReconciliationRepository_LinkEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockReconciliationRepository_LinkEvidence_Call) Return(_a0 error) *MockReconciliationRepository_LinkEvidence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReconciliationRepository_LinkEvidence_Call) RunAndReturn(run func(context.Context, string, string) error) *MockReconciliationRepository_LinkEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, proposal
func (_m *MockReconciliationRepository) Save(ctx context.Context, proposal knowledge.ReconciliationProposal) error {
	ret := _m.Called(ctx, proposal)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.ReconciliationProposal) error); ok {
		r0 = rf(ctx, proposal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReconciliationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockReconciliationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - proposal knowledge.ReconciliationProposal
func (_e *MockReconciliationRepository_Expecter) Save(ctx interface{}, proposal interface{}) *MockReconciliationRepository_Save_Call {
	return &MockReconciliationRepository_Save_Call{Call: _e.mock.On("Save", ctx, proposal)}
}

func (_c *MockReconciliationRepository_Save_Call) Run(run func(ctx context.Context, proposal knowledge.ReconciliationProposal)) *MockReconciliationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.ReconciliationProposal))
	})
	return _c
}

func (_c *MockReconciliationRepository_Save_Call) Return(_a0 error) *MockReconciliationRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReconciliationRepository_Save_Call) RunAndReturn(run func(context.Context, knowledge.ReconciliationProposal) error) *MockReconciliationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReconciliationRepository creates a new instance of MockReconciliationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReconciliationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReconciliationRepository {
	mock := &MockReconciliationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
