// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockEvidenceRepository is an autogenerated mock type for the EvidenceRepository type
type MockEvidenceRepository struct {
	mock.Mock
}

type MockEvidenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvidenceRepository) EXPECT() *MockEvidenceRepository_Expecter {
	return &MockEvidenceRepository_Expecter{mock: &_m.Mock}
}

// DeleteUnreferenced provides a mock function with given fields: ctx
func (_m *MockEvidenceRepository) DeleteUnreferenced(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnreferenced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEvidenceRepository_DeleteUnreferenced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnreferenced'
type MockEvidenceRepository_DeleteUnreferenced_Call struct {
	*mock.Call
}

// DeleteUnreferenced is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEvidenceRepository_Expecter) DeleteUnreferenced(ctx interface{}) *MockEvidenceRepository_DeleteUnreferenced_Call {
	return &MockEvidenceRepository_DeleteUnreferenced_Call{Call: _e.mock.On("DeleteUnreferenced", ctx)}
}

func (_c *MockEvidenceRepository_DeleteUnreferenced_Call) Run(run func(ctx context.Context)) *MockEvidenceRepository_DeleteUnreferenced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEvidenceRepository_DeleteUnreferenced_Call) Return(_a0 error) *MockEvidenceRepository_DeleteUnreferenced_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvidenceRepository_DeleteUnreferenced_Call) RunAndReturn(run func(context.Context) error) *MockEvidenceRepository_DeleteUnreferenced_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, evidence
func (_m *MockEvidenceRepository) GetOrCreate(ctx context.Context, evidence knowledge.Evidence) (knowledge.Evidence, error) {
	ret := _m.Called(ctx, evidence)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 knowledge.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Evidence) (knowledge.Evidence, error)); ok {
		return rf(ctx, evidence)
	}
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Evidence) knowledge.Evidence); ok {
		r0 = rf(ctx, evidence)
	} else {
		r0 = ret.Get(0).(knowledge.Evidence)
	}

	if rf, ok := ret.Get(1).(func(context.Context, knowledge.Evidence) error); ok {
		r1 = rf(ctx, evidence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvidenceRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockEvidenceRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - evidence knowledge.Evidence
func (_e *MockEvidenceRepository_Expecter) GetOrCreate(ctx interface{}, evidence interface{}) *MockEvidenceRepository_GetOrCreate_Call {
	return &MockEvidenceRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, evidence)}
}

func (_c *MockEvidenceRepository_GetOrCreate_Call) Run(run func(ctx context.Context, evidence knowledge.Evidence)) *MockEvidenceRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.Evidence))
	})
	return _c
}

func (_c *MockEvidenceRepository_GetOrCreate_Call) Return(_a0 knowledge.Evidence, _a1 error) *MockEvidenceRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvidenceRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, knowledge.Evidence) (knowledge.Evidence, error)) *MockEvidenceRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// LinkToItem provides a mock function with given fields: ctx, link
func (_m *MockEvidenceRepository) LinkToItem(ctx context.Context, link knowledge.ItemEvidence) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for LinkToItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.ItemEvidence) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEvidenceRepository_LinkToItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkToItem'
type MockEvidenceRepository_LinkToItem_Call struct {
	*mock.Call
}

// LinkToItem is a helper method to define mock.On call
//   - ctx context.Context
//   - link knowledge.ItemEvidence
func (_e *MockEvidenceRepository_Expecter) LinkToItem(ctx interface{}, link interface{}) *MockEvidenceRepository_LinkToItem_Call {
	return &MockEvidenceRepository_LinkToItem_Call{Call: _e.mock.On("LinkToItem", ctx, link)}
}

func (_c *MockEvidenceRepository_LinkToItem_Call) Run(run func(ctx context.Context, link knowledge.ItemEvidence)) *MockEvidenceRepository_LinkToItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.ItemEvidence))
	})
	return _c
}

func (_c *MockEvidenceRepository_LinkToItem_Call) Return(_a0 error) *MockEvidenceRepository_LinkToItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvidenceRepository_LinkToItem_Call) RunAndReturn(run func(context.Context, knowledge.ItemEvidence) error) *MockEvidenceRepository_LinkToItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListByItem provides a mock function with given fields: ctx, itemID
func (_m *MockEvidenceRepository) ListByItem(ctx context.Context, itemID string) ([]knowledge.Evidence, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for ListByItem")
	}

	var r0 []knowledge.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]knowledge.Evidence, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []knowledge.Evidence); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]knowledge.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvidenceRepository_ListByItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByItem'
type MockEvidenceRepository_ListByItem_Call struct {
	*mock.Call
}

// ListByItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID string
func (_e *MockEvidenceRepository_Expecter) ListByItem(ctx interface{}, itemID interface{}) *MockEvidenceRepository_ListByItem_Call {
	return &MockEvidenceRepository_ListByItem_Call{Call: _e.mock.On("ListByItem", ctx, itemID)}
}

func (_c *MockEvidenceRepository_ListByItem_Call) Run(run func(ctx context.Context, itemID string)) *MockEvidenceRepository_ListByItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEvidenceRepository_ListByItem_Call) Return(_a0 []knowledge.Evidence, _a1 error) *MockEvidenceRepository_ListByItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvidenceRepository_ListByItem_Call) RunAndReturn(run func(context.Context, string) ([]knowledge.Evidence, error)) *MockEvidenceRepository_ListByItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvidenceRepository creates a new instance of MockEvidenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvidenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvidenceRepository {
	mock := &MockEvidenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
