// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageSourceRepository is an autogenerated mock type for the MessageSourceRepository type
type MockMessageSourceRepository struct {
	mock.Mock
}

type MockMessageSourceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSourceRepository) EXPECT() *MockMessageSourceRepository_Expecter {
	return &MockMessageSourceRepository_Expecter{mock: &_m.Mock}
}

// ListBySession provides a mock function with given fields: ctx, sessionID
func (_m *MockMessageSourceRepository) ListBySession(ctx context.Context, sessionID string) (map[string][]knowledge.Source, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySession")
	}

	var r0 map[string][]knowledge.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string][]knowledge.Source, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string][]knowledge.Source); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]knowledge.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageSourceRepository_ListBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySession'
type MockMessageSourceRepository_ListBySession_Call struct {
	*mock.Call
}

// ListBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockMessageSourceRepository_Expecter) ListBySession(ctx interface{}, sessionID interface{}) *MockMessageSourceRepository_ListBySession_Call {
	return &MockMessageSourceRepository_ListBySession_Call{Call: _e.mock.On("ListBySession", ctx, sessionID)}
}

func (_c *MockMessageSourceRepository_ListBySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockMessageSourceRepository_ListBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageSourceRepository_ListBySession_Call) Return(_a0 map[string][]knowledge.Source, _a1 error) *MockMessageSourceRepository_ListBySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageSourceRepository_ListBySession_Call) RunAndReturn(run func(context.Context, string) (map[string][]knowledge.Source, error)) *MockMessageSourceRepository_ListBySession_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, messageID, sources
func (_m *MockMessageSourceRepository) Save(ctx context.Context, messageID string, sources []knowledge.Source) error {
	ret := _m.Called(ctx, messageID, sources)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []knowledge.Source) error); ok {
		r0 = rf(ctx, messageID, sources)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageSourceRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMessageSourceRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
//   - sources []knowledge.Source
func (_e *MockMessageSourceRepository_Expecter) Save(ctx interface{}, messageID interface{}, sources interface{}) *MockMessageSourceRepository_Save_Call {
	return &MockMessageSourceRepository_Save_Call{Call: _e.mock.On("Save", ctx, messageID, sources)}
}

func (_c *MockMessageSourceRepository_Save_Call) Run(run func(ctx context.Context, messageID string, sources []knowledge.Source)) *MockMessageSourceRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]knowledge.Source))
	})
	return _c
}

func (_c *MockMessageSourceRepository_Save_Call) Return(_a0 error) *MockMessageSourceRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageSourceRepository_Save_Call) RunAndReturn(run func(context.Context, string, []knowledge.Source) error) *MockMessageSourceRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSourceRepository creates a new instance of MockMessageSourceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSourceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSourceRepository {
	mock := &MockMessageSourceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
