// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	knowledge "github.com/santaniello/athena/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// MockRelationRepository is an autogenerated mock type for the RelationRepository type
type MockRelationRepository struct {
	mock.Mock
}

type MockRelationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelationRepository) EXPECT() *MockRelationRepository_Expecter {
	return &MockRelationRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, relation
func (_m *MockRelationRepository) Save(ctx context.Context, relation knowledge.Relation) error {
	ret := _m.Called(ctx, relation)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, knowledge.Relation) error); ok {
		r0 = rf(ctx, relation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRelationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRelationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - relation knowledge.Relation
func (_e *MockRelationRepository_Expecter) Save(ctx interface{}, relation interface{}) *MockRelationRepository_Save_Call {
	return &MockRelationRepository_Save_Call{Call: _e.mock.On("Save", ctx, relation)}
}

func (_c *MockRelationRepository_Save_Call) Run(run func(ctx context.Context, relation knowledge.Relation)) *MockRelationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(knowledge.Relation))
	})
	return _c
}

func (_c *MockRelationRepository_Save_Call) Return(_a0 error) *MockRelationRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRelationRepository_Save_Call) RunAndReturn(run func(context.Context, knowledge.Relation) error) *MockRelationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRelationRepository creates a new instance of MockRelationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelationRepository {
	mock := &MockRelationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
