// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQueryEnricher is an autogenerated mock type for the QueryEnricher type
type MockQueryEnricher struct {
	mock.Mock
}

type MockQueryEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryEnricher) EXPECT() *MockQueryEnricher_Expecter {
	return &MockQueryEnricher_Expecter{mock: &_m.Mock}
}

// Enrich provides a mock function with given fields: ctx, sessionID, topic, content
func (_m *MockQueryEnricher) Enrich(ctx context.Context, sessionID string, topic string, content string) (string, error) {
	ret := _m.Called(ctx, sessionID, topic, content)

	if len(ret) == 0 {
		panic("no return value specified for Enrich")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, sessionID, topic, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, sessionID, topic, content)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, sessionID, topic, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryEnricher_Enrich_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enrich'
type MockQueryEnricher_Enrich_Call struct {
	*mock.Call
}

// Enrich is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - topic string
//   - content string
func (_e *MockQueryEnricher_Expecter) Enrich(ctx interface{}, sessionID interface{}, topic interface{}, content interface{}) *MockQueryEnricher_Enrich_Call {
	return &MockQueryEnricher_Enrich_Call{Call: _e.mock.On("Enrich", ctx, sessionID, topic, content)}
}

func (_c *MockQueryEnricher_Enrich_Call) Run(run func(ctx context.Context, sessionID string, topic string, content string)) *MockQueryEnricher_Enrich_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockQueryEnricher_Enrich_Call) Return(_a0 string, _a1 error) *MockQueryEnricher_Enrich_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryEnricher_Enrich_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockQueryEnricher_Enrich_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryEnricher creates a new instance of MockQueryEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryEnricher {
	mock := &MockQueryEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
