// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	llm "github.com/fsantaniello/athena_school/internal/platform/llm"
	mock "github.com/stretchr/testify/mock"
)

// LLMProvider is an autogenerated mock type for the LLMProvider type
type LLMProvider struct {
	mock.Mock
}

// Chat provides a mock function with given fields: ctx, req
func (_m *LLMProvider) Chat(ctx context.Context, req llm.ChatRequest) (llm.ChatResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 llm.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.ChatRequest) (llm.ChatResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, llm.ChatRequest) llm.ChatResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(llm.ChatResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, llm.ChatRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLLMProvider creates a new instance of LLMProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLLMProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *LLMProvider {
	mock := &LLMProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
