// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	study "github.com/santaniello/athena/internal/domain/study"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockSessionRepository) Create(ctx context.Context, session study.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, study.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session study.Session
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, session study.Session)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(study.Session))
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(_a0 error) *MockSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(context.Context, study.Session) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// End provides a mock function with given fields: ctx, id, endedAt
func (_m *MockSessionRepository) End(ctx context.Context, id string, endedAt time.Time) error {
	ret := _m.Called(ctx, id, endedAt)

	if len(ret) == 0 {
		panic("no return value specified for End")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, endedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type MockSessionRepository_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - endedAt time.Time
func (_e *MockSessionRepository_Expecter) End(ctx interface{}, id interface{}, endedAt interface{}) *MockSessionRepository_End_Call {
	return &MockSessionRepository_End_Call{Call: _e.mock.On("End", ctx, id, endedAt)}
}

func (_c *MockSessionRepository_End_Call) Run(run func(ctx context.Context, id string, endedAt time.Time)) *MockSessionRepository_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepository_End_Call) Return(_a0 error) *MockSessionRepository_End_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_End_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockSessionRepository_End_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
