// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	study "github.com/santaniello/athena/internal/domain/study"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, message
func (_m *MockMessageRepository) Append(ctx context.Context, message study.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, study.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockMessageRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - message study.Message
func (_e *MockMessageRepository_Expecter) Append(ctx interface{}, message interface{}) *MockMessageRepository_Append_Call {
	return &MockMessageRepository_Append_Call{Call: _e.mock.On("Append", ctx, message)}
}

func (_c *MockMessageRepository_Append_Call) Run(run func(ctx context.Context, message study.Message)) *MockMessageRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(study.Message))
	})
	return _c
}

func (_c *MockMessageRepository_Append_Call) Return(_a0 error) *MockMessageRepository_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_Append_Call) RunAndReturn(run func(context.Context, study.Message) error) *MockMessageRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySession provides a mock function with given fields: ctx, sessionID
func (_m *MockMessageRepository) ListBySession(ctx context.Context, sessionID string) ([]study.Message, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySession")
	}

	var r0 []study.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]study.Message, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []study.Message); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]study.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_ListBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySession'
type MockMessageRepository_ListBySession_Call struct {
	*mock.Call
}

// ListBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockMessageRepository_Expecter) ListBySession(ctx interface{}, sessionID interface{}) *MockMessageRepository_ListBySession_Call {
	return &MockMessageRepository_ListBySession_Call{Call: _e.mock.On("ListBySession", ctx, sessionID)}
}

func (_c *MockMessageRepository_ListBySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockMessageRepository_ListBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageRepository_ListBySession_Call) Return(_a0 []study.Message, _a1 error) *MockMessageRepository_ListBySession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_ListBySession_Call) RunAndReturn(run func(context.Context, string) ([]study.Message, error)) *MockMessageRepository_ListBySession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
